<i class="fa-solid fs-27px p-9-5 fa-angle-double-down" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-angle-double-up d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-angle-down" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-angle-up d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-arrow-alt-circle-down" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-arrow-alt-circle-up d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-arrow-circle-down" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-arrow-circle-up d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-arrow-down" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-arrow-up d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-chevron-down" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-chevron-up d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-caret-square-down" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-caret-square-up d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-caret-down" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-caret-up d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-chevron-circle-down" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-chevron-circle-up d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-plus" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-minus d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-plus-square" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-minus-square d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-level-down-alt" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-level-up-alt d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-clipboard-check" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-clipboard d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-hand-point-right" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-hand-point-up d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-plus-circle" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-minus-circle d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-long-arrow-alt-down" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-long-arrow-alt-up d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-search-plus" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-search-minus d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-folder-plus" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-folder-minus d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-door-closed" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-door-open d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-envelope" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-envelope-open d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-cogs" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-cog d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-cookie-bite" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-cookie d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-folder-open" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-folder d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-fill-drip" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-fill d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-toggle-off" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-toggle-on d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-laptop-medical" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-laptop d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-lock" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-lock-open d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-hourglass-end" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-hourglass d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-microphone-alt" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-microphone d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-phone-square-alt" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-phone-square d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-phone-alt" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-phone d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-prescription-bottle-alt" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-prescription-bottle d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-question-circle" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-question d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-radiation-alt" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-radiation d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-tags" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-tag d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-plane-departure" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-plane d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-plane-arrival" onclick="changeIcon(this)"></i>
<i class="fa-solid fs-27px p-9-5 fa-fighter-jet d-none"></i>
<i class="fa-solid fs-27px p-9-5 fa-check" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-check-circle" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-clinic-medical" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-gift" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-glasses" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-helicopter" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-hotel" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-key" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-paper-plane" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-parachute-box" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-paw" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-pepper-hot" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-pizza-slice" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-plug" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-podcast" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-portrait" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-pound-sign" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-power-off" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-bolt" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-project-diagram" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-puzzle-piece" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-receipt" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-recycle" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-ribbon" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-robot" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-rocket" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-route" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-rss-square" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-rupee-sign" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-satellite-dish" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-school" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-screwdriver" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-scroll" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-search-dollar" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-search-location" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-seedling" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-shapes" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-shield-alt" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-shield-virus" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-ship" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-shipping-fast" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-shoe-prints" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-shopping-bag" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-shopping-cart" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-shuttle-van" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-sign" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-smile" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-snowflake" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-snowman" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-spa" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-spell-check" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-star" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-stethoscope" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-suitcase" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-sun" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-surprise" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-syringe" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-table-tennis" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-tablets" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-tachometer-alt" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-tasks" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-thumbtack" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-directions" onclick="changeIcon(this,true)"></i>
<i class="fa-solid fs-27px p-9-5 fa-thumbtack d-none" ></i>